In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import itertools

import warnings
warnings.filterwarnings('ignore')

## Tutorial on Active Inference
Based on https://medium.com/@solopchuk/tutorial-on-active-inference-30edcf50f5dc

### Helper functions

In [14]:
def softmax(x):
    return np.exp(x) / sum(np.exp(x))

def KL(a, b):
    # Kullback-Leibler divergence
    # From https://datascience.stackexchange.com/questions/9262/calculating-kl-divergence-in-python
    a = np.asarray(a, dtype=np.float)
    b = np.asarray(b, dtype=np.float)

    return np.sum(np.where(a != 0, a * np.log(a / b), 0))

def H(p):
    # Ambiguity
    p = np.array(p)
    H = np.sum(np.where(p != 0, p * np.log(p), 0))

    return H

def mutual_information(p, a, b):
    pass

10.289216058526625

In [ ]:
######## Generative model #############################

# The generative model p(o, s)

# Index 0: probability of EITHER observation "hungry"
#           OR true hidden state "hungry"
#           OR action "do nothing"

# Index 1: probability of EITHER observation "full"
#           OR true hidden state "full"
#           OR action "eat"

# Prior preferences on observations
# p(o)

p_obs = [0.99, 0.01]


# Prior belief on hidden states
# p(s)
# Not used

p_states = [0.5, 0.5]

# Likelihood p(observation | state)
# A[y, x]
# Y-axis: state
# X-axis: observation

A = np.array([[0.9, 0.1], [0.3, 0.7]])
#A = np.array([[1, 0], [0, 1]])

# Transition probability p(state_t | state_t-1, action)
# B[x, y, z]
# X-axis: Current state (at t)
# Y-axis: action
# Z-axis: Next state (at t+1)

B = np.array([[[0.8, 0.2], [0.3, 0.7]],[[0.6, 0.4], [0.15, 0.85]]])
#B = np.array([[[0.9999, 0.0001], [0.0001, 0.9999]],[[0.9999, 0.0001], [0.0001, 0.9999]]])

In [3]:
def KL(a, b):
    # Kullback-Leibler divergence
    # From https://datascience.stackexchange.com/questions/9262/calculating-kl-divergence-in-python
    a = np.asarray(a, dtype=np.float)
    b = np.asarray(b, dtype=np.float)

    return np.sum(np.where(a != 0, a * np.log(a / b), 0))

In [33]:
p = np.array([0.6, 0.4])
p_obs = np.broadcast_to(p, (3, 2))
arr1 = np.array([0, 1])
arr2 = np.array([[0, 1], [0.9, 0.1]])
arr3 = np.array([[0, 1], [0.9, 0.1], [0.65, 0.35]])

In [39]:
KL(arr1, p_obs[0])

0.9162907318741551

In [40]:
KL(arr2, p_obs[:2])

1.142579893059514

In [41]:
KL(arr3, p_obs)

1.1478716656287298

In [26]:
a = np.arange(6).reshape(3,2)
b = np.arange(4).reshape(2, 2)

In [42]:
p_obs[0]

array([0.6, 0.4])

In [28]:
a[-1] @ b

array([10, 19])

In [38]:
p_obs[:2]

array([[0.6, 0.4],
       [0.6, 0.4]])

In [ ]:
p_obs = 